fn main() {
    Failures    fn foo() {}
}
